package com.anttek.slack.callback.model

class MessageEventPreviousMessageFile (
    var preview: Any,
    var filetype: String,
    var title: String,
    var ims: ArrayList<Any>,
    var mode: String,
    var urlPrivate: String,
    var id: String,
    var state: String,
    var displayAsBot: Boolean,
    var timestamp: Long,
    var editor: String,
    var created: Long,
    var editable: Boolean,
    var lastEditor: String,
    var groups: ArrayList<Any>,
    var isExternal: Boolean,
    var prettyType: String,
    var externalType: String,
    var urlPrivateDownload: String,
    var permalinkPublic: String,
    var channels: ArrayList<String>,
    var size: Long,
    var commentsCount: Long,
    var isPublic: Boolean,
    var name: String,
    var mimetype: String,
    var permalink: String,
    var publicUrlShared: Boolean,
    var updated: Long,
    var user: String,
    var username: String
)
