package com.anttek.slack.api.model

class UserProfile (
    var image32: String? = null,
    var statusEmoji: String? = null,
    var guestInvitedBy: String? = null,
    var apiAppId: String? = null,
    var image192: String? = null,
    var realName: String,
    var title: String? = null,
    var statusTextCanonical: String? = null,
    var skype: String? = null,
    var imageOriginal: String? = null,
    var guestChannels: String? = null,
    var guestExpirationTs: Long? = null,
    var realNameNormalized: String,
    var avatarHash: String,
    var firstName: String? = null,
    var botId: String? = null,
    var email: String? = null,
    var image512: String? = null,
    var image1024: String? = null,
    var teams: String? = null,
    var image24: String? = null,
    var lastName: String? = null,
    var image48: String? = null,
    var team: String? = null,
    var displayName: String,
    var alwaysActive: Boolean? = null,
    var statusExpiration: Long? = null,
    var phone: String? = null,
    var isCustomImage: Boolean? = null,
    var statusText: String? = null,
    var image72: String? = null,
    var displayNameNormalized: String
)
